community/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import signup
from .views import new_comment
from .views import *

app_name = 'community'


urlpatterns = [
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),

    # mypage관련 url
    path('mypage/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('cancelScrap/', views.UserDetail.cancel_scrap),
    path('mypage/<int:pk>/modKeyword/', views.modKeyWord, name='modKeyword'),
    path('keywords/', views.get_keywords),
    path('saveKeywords/<int:pk>/', views.save_keywords, name='save_keywords'),
    path('mypage/<int:pk>/modMajor/', views.modMajor, name='modMajor'),
    path('saveMajors/<int:pk>/', views.save_majors, name='save_majors'),
    path('myteamPage/<int:pk>/', views.myTeam, name='myTeam_detail'),
    path('myCommentPage/<int:pk>/', views.myComment, name='my_comment'),
    path('deleteTeam/', views.UserDetail.delete_team),


    path('recommend/<int:pk>/', views.Recommend.as_view(), name='recommend'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='community/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('check_scrap_status/<int:post_id>/', views.check_scrap_status, name='check_scrap_status'),
    path('scrap/<int:post_id>/', views.toggle_scrap, name='toggle_scrap'),

    path('team/', views.TeamList.as_view(), name='team_list'),  # 팀 전체 게시판 url
    path('team/<int:pk>/', views.TeamDetail.as_view(), name='team_detail'),  # 팀 모집글 detail 페이지
    path('team_post/', views.TeamPostForm.as_view(template_name='community/team_post_form.html'), name="TeamPostForm"), #팀 모집글 작성 Form
    path('team/<int:pk>/new_comment/', views.new_comment, name='new_comment'), #팀 모집 댓글 url
    path('<int:pk>/post_team/', views.post_team, name='post_team'), # post에서 해당 팀 모집글 리스트 보기
    
     path('search/', views.search, name='search'),

]

ds_DjangoTeam01/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('', include('single_pages.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect

from community.models import User, Comment, Post, Team  # community 앱의 User 모델을 import + Comment , Post 모델도

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")


class TeamPostForm(forms.ModelForm):
    post = forms.ModelChoiceField(
        queryset=Post.objects.all(),
        empty_label=None,
        to_field_name='id',
    )

    class Meta:
        model = Team
        fields = ['post', 'title', 'content']

    def __init__(self, user, post_id, *args, **kwargs):
        super(TeamPostForm, self).__init__(*args, **kwargs)
        self.user = user

        # post_id를 이용하여 Post 객체 가져오기 (기본값 사용)
        post_instance = get_object_or_404(Post, id=post_id) if post_id else None

        # 폼의 post 필드 초기값 설정
        self.fields['post'].initial = post_instance

        self.fields['title'].label = '제목'
        self.fields['content'].label = '내용'
        self.fields['post'].label = '활동명'
        
    def save(self, commit=True):
        instance = super().save(commit=False)
        current_user = self.user

        if current_user.is_authenticated:
            post_instance_pk = self.cleaned_data['post'].id  # post 필드에 해당하는 Post 객체의 primary key

            try:
                post_instance = Post.objects.get(pk=post_instance_pk)
                instance.post = post_instance

                # 괄호 안의 내용을 제거하는 방식
                import re
                cleaned_post_title = re.sub(r'\[\d+\]', '', str(post_instance)).strip()

                user_input_title = self.cleaned_data['title']
                combined_title = f"[{cleaned_post_title}] {user_input_title}"
                instance.title = user_input_title

                instance.user = current_user
                if commit:
                    instance.save()
                return instance
            
            except Post.DoesNotExist:
                # Post 객체를 찾을 수 없는 경우
                return None
        else:
            # 인증되지 않은 사용자에 대한 처리 (예: 리디렉션)
            return redirect('/community')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

    def __init__(self, user, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.user = user
        
        self.fields['content'].label = '댓글 작성'

    def save(self, commit=True):
        instance = super(CommentForm, self).save(commit=False)
        instance.user = self.user  # 사용자 정보 설정
        if commit:
            instance.save()
        return instance

community/views.py
from audioop import reverse

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from .models import Post, User, Team, Major, Keyword , Comment, Scrap
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.db.models import Q
from .forms import UserForm, CommentForm, TeamPostForm
from django.contrib.auth import authenticate,login
from django.http import JsonResponse
from functools import reduce
import operator 
from random import random, choice 
from collections import Counter
import os
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# ------------------------------------------------------------------------------------->
class PostList(ListView):
    model = Post
    template_name = 'community/post_list.html'
    context_object_name = 'post_list'
    paginate_by = 10  # 페이지당 post 10개 반환
    
# -----교내/대외/전체 필터링------------------------------------------>
    def get_queryset(self):
        filter_value = self.request.GET.get('filter', 'all')

        if filter_value == 'isduksung':
            return Post.objects.filter(isduksung=True).order_by('-time')
        elif filter_value == 'notIsduksung':
            return Post.objects.filter(isduksung=False).order_by('-time')
        else:
            return Post.objects.all().order_by('-time')
        
# -----페이지네이션---------------------------------------------------->
    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)

        paginator = context['paginator']
        page = context['page_obj']
        is_paginated = context['is_paginated']

        try:
            current_page = int(self.request.GET.get('page', 1))
        except ValueError:
            current_page = 1

        max_pages = 5  # 페이지당 페이징 버튼 수
        start_page = max(1, current_page - ((current_page - 1) % max_pages))
        end_page = min(start_page + max_pages - 1, paginator.num_pages)
        page_range = range(start_page, end_page + 1)

        context.update({
            'page_range': page_range,
        })

        try:
            previous_page = page.previous_page_number()
        except EmptyPage:
            previous_page = None

        try:
            next_page = page.next_page_number()
        except EmptyPage:
            next_page = None

        context.update({
            'previous_page': previous_page,
            'next_page': next_page,
            'first_page': 1,
            'last_page': paginator.num_pages,
            'filter_value': self.request.GET.get('filter', 'all'),
        })
        
        return context

# ------------------------------------------------------------------------------------------->

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        return context
    
# ------------------------------------------------------------------------------------------->

class UserDetail(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'community/user_detail.html'  

    def get_context_data(self, **kwargs):
        context = super(UserDetail, self).get_context_data(**kwargs)

        # 현재 로그인된 사용자의 정보 가져오기
        current_user = self.request.user

        # 예시: 로그인된 사용자의 관심전공 목록
        context['current_user_majors'] = current_user.major.all()

        # 예시: 로그인된 사용자의 맞춤 키워드 목록
        context['current_user_keywords'] = current_user.keyword.all()

        # 예시: 로그인된 사용자가 스크랩한 활동 목록
        context['current_user_scraps'] = current_user.scrap_set.all()

        selected_images = Recommend.get_dukse_images()

        context.update({
            'selected_images': selected_images,
        })

        return context
    
    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        
        # 로그인한 사용자와 조회하려는 사용자가 다를 경우 404 에러 반환
        if obj != self.request.user:
            raise Http404("You don't have permission to access this page")
        
        return obj
    
    def cancel_scrap(request):
        post_id = request.GET.get('postId')
        post = get_object_or_404(Post, pk=post_id)
        user = request.user

        Scrap.objects.filter(user=user, post=post).delete()
        return JsonResponse({'message': 'Success'})
    
    def delete_team(request):
        post_id = request.GET.get('postId')
        post = get_object_or_404(Post, pk=post_id)
        user = request.user
        Team.objects.filter(user=user, post=post).delete()
        return JsonResponse({'message': 'Success'})
                
    
    
# 키워드 수정 페이지로 이동   
def modKeyWord(request, pk):
    user = User.objects.get(id=pk)
    if request.user != user:
        raise Http404("You don't have permission to access this page")

    return render(
        request,
        'community/modKeyword.html',
    )

# 카테고리에 맞는 키워드 가져오기
def get_keywords(request):
    category = request.GET.get('category')

    if category == '1':
        category_keywords = Keyword.objects.filter(category='활동 분야')
    elif category == '2':
        category_keywords = Keyword.objects.filter(category='언론/미디어')
    elif category == '3':
        category_keywords = Keyword.objects.filter(category='디자인/사진/예술/영상')
    elif category == '4':
        category_keywords = Keyword.objects.filter(category='경제/금융')
    elif category == '5':
        category_keywords = Keyword.objects.filter(category='경영/컨설팅')
    elif category == '6':
        category_keywords = Keyword.objects.filter(category='과학/공학/기술/IT')

    keyword_data = {'keywords': list(category_keywords.values())}
    return JsonResponse(keyword_data)

# 디폴트 키워드 & 사용자가 입력한 키워드 저장하기
def save_keywords(request, pk):
    user = get_object_or_404(User, pk=pk)
    
    if request.method == 'POST':
        user.keyword.clear()

        make_keywords = request.POST.get('make_keywords').split(',')
        default_keywords = request.POST.get('default_keywords').split(',')

        for dk in default_keywords:
            if dk.strip() != '':
                try:
                    default_keywords_obj = Keyword.objects.get(keywordname=dk)
                    user.keyword.add(default_keywords_obj.id)
                except Keyword.DoesNotExist:
                    raise Http404("원하는 키워드를 찾을 수 없습니다.")

        for mk in make_keywords:
            if mk.strip() != '':
                try:
                    make_keyword_obj, created = Keyword.objects.get_or_create(keywordname=mk, defaults={'ismake': True, 'category': None})
                    user.keyword.add(make_keyword_obj.id)
                except Keyword.DoesNotExist:
                    new_keyword = Keyword.objects.create(keywordname=mk, ismake=True, category=None)
                    user.keyword.add(new_keyword.id)


        return redirect('community:user_detail', pk=pk)
    
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})
    

# 관심전공 수정 페이지로 이동
def modMajor(request, pk):
    majors = Major.objects.all()
    user = User.objects.get(id=pk)
    user_major = user.major.all()

    if request.user != user:
        raise Http404("You don't have permission to access this page")


    return render(
        request,
        'community/modMajor.html',
        {
            'majors' : majors,
            'user_major' : user_major,
        }
    )

# 관심전공 저장하기
def save_majors(request, pk):
    user = get_object_or_404(User, pk=pk)

    if request.method == 'POST':
        user.major.clear()

        selected_majors = request.POST.getlist('majors[]')
        for major_id in selected_majors:
            user.major.add(major_id)

        return redirect('community:user_detail', pk=pk)
    
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})

# 내가 쓴 글 페이지로 이동
def myTeam(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        raise Http404("You don't have permission to access this page")

    try:
        teams = Team.objects.filter(user=user)
    except Team.DoesNotExist:
        teams = None

    return render(
        request,
        'community/my_team.html',
        {
            'user' : user,
            'teams' : teams,
        }
    )

# 내가 쓴 댓글 페이지로 이동
def myComment(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        raise Http404("You don't have permission to access this page")

    try:
        comments = Comment.objects.filter(user=user)
    except Team.DoesNotExist:
        comments = None

    return render(
        request,
        'community/my_team_comment.html',
        {
            'user' : user,
            'comments' : comments,
        }
    )


    


# 바뀐 user를 보고  바꾸는 test
class Recommend(LoginRequiredMixin, ListView):
    model = User
    template_name = 'community/recommend_list.html'
    ordering = '-pk'

    @classmethod
    def get_dukse_images(cls):
        dukse_images_path = os.path.join('community', 'static', 'community', 'dukse')
        dukse_images = [f for f in os.listdir(dukse_images_path) if f.endswith(('.jpg', '.jpeg', '.png'))]
        selected_images = [choice(dukse_images) for _ in range(8)]

        return selected_images

    def get_context_data(self, **kwargs):
        context = super(Recommend, self).get_context_data(**kwargs)

        # 현재 로그인된 사용자의 정보 가져오기
        current_user = self.request.user

        #-----------------------추천 posts-----------------------------
        # 사용자가 선택한 키워드에 맞는 게시글 10개 가져오기
        selected_keywords = current_user.keyword.all()

        posts_dic = {}
        for keyword in selected_keywords:

community/templates/community/navbar.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">

<style>
    * {
    margin: 0;
    padding: 0;
    }


    /* 덕잡 font 폰트 */
    .container-fluid {
        font-family: 'NanumSquareAceb';
    }

    .navbar {
        background-color: #fff; /* 네비바 전체의 배경색을 흰색으로 설정 */
        border-bottom: 1px solid #ddd;
        font-family: 'NanumSquareExtraBold';
    }

    .navbar-brand {
        font-size: 1.5rem;
        font-weight: bold;
        color: #5A32FB;
        margin-right: auto;
    }

    .navbar-toggler {
        border-color: #5A32FB;
    }

    .navbar-nav {
        margin-left: auto;
    }

    /* 네비바 font 폰트 */
    .navbar-nav .nav-link {
        color: #1E1E1E; /* NAV-ITEM 글씨체를 짙은 회색으로 설정 */
        font-weight: 500;
        font-family: 'NanumSquareExtraBold';
        transition: color 0.3s;
        margin: 0 5px;
    }


    .navbar-nav .nav-link:hover {
        color: #5A32FB;
    }

    .navbar-nav .active {
        background-color: #5A32FB;
        border-radius: 8px;
    }

    .navbar-nav .active .nav-link {
        color: #fff;
    }

    /* 로그인 로그아웃 버튼 font 폰트 */
    .login-btn, .logout-btn {
        font-family: 'NanumSquareAcb';
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 8px 15px;
        border-radius: 10px;
        text-decoration: none;
        font-weight: 500;
        transition: background-color 0.3s;
    }

    .login-btn {
        background-color: #5A32FB;
        color: #fff;
    }

    .login-btn:hover {
        background-color: #3e1eaf;
    }

    .logout-btn {
        background-color: #5A32FB;
        color: #fff;
    }

    .logout-btn:hover {
        background-color: #7b848a;
    }

    .navbar-nav .nav-link.active {
        background-color: transparent;
        color: #5A32FB;
    }


</style>

<div class="m-4">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a href="/" class="navbar-brand">DUKJOB</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="/about_we/" class="nav-item nav-link">서비스 소개</a>
                    <a href="/community/" class="nav-item nav-link">활동 목록</a>
                    
                    {% if user.is_authenticated %}
                        <a href="{% url 'community:recommend' pk=user.pk %}" class="nav-item nav-link">추천활동</a>
                    {% else %}
                        <a href="{% url 'community:login' %}" class="nav-item nav-link">추천활동</a>
                    {% endif %}

                    <a href="/community/team" class="nav-item nav-link">팀원모집</a>


                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'community:user_detail' pk=user.pk %}">마이페이지</a>
                    {% else %}
                        <a href="{% url 'community:signup' %}" class="nav-item nav-link">회원가입</a>
                    {% endif %}
                    
                    <div class="nav-item nav-link">
                        {% if user.is_authenticated %}
                            <a href="{% url 'community:logout' %}" class="logout-btn">Logout</a>
                        {% else %}
                            <a href="{% url 'community:login' %}" class="login-btn">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

community/templates/community/new_teamlist_test.html
<!-- http://127.0.0.1:8000/community -->
<link rel="stylesheet" href="../../static/community/css/community.css"/>

{% extends 'community/base.html' %}

{% block scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // 페이지가 로드될 때 실행되는 코드
            // 이 부분에 클라이언트 측 JavaScript 코드를 작성

            // 클릭 이벤트를 사용하여 data-filter 값을 확인하고 필터링
            var filterItems = document.querySelectorAll('.choose_one li');

            filterItems.forEach(function (item) {
                item.addEventListener('click', function () {
                    var filterValue = item.getAttribute('data-filter');

                    // 필터 적용을 위한 함수 호출
                    applyFilter(filterValue);
                });
            });

            function applyFilter(filter) {
                // 이 부분에서 실제 필터링을 구현
                // filter 값에 따라 적절한 처리를 수행
                var tableRows = document.querySelectorAll('.list_table tbody tr');

                tableRows.forEach(function (row) {
                    var dataFilter = row.getAttribute('data-filter');

                    // 모든 행을 숨김
                    row.style.display = 'none';

                    // 선택된 필터와 일치하는 경우 해당 행을 보여줌
                    if (filter === 'all' || dataFilter === filter) {
                        row.style.display = '';
                    }
                });
            }

            // 글쓰기 버튼 클릭 이벤트 처리
            document.getElementById('createPostBtn').addEventListener('click', function () {
                var isLoggedIn = {% if user.is_authenticated %} true {% else %} false {% endif %};

                if (isLoggedIn) {
                    // 로그인된 경우
                    var teamPostFormUrl = "{% url 'community:TeamPostForm' %}";
                    window.location.href = teamPostFormUrl;
                } else {
                    // 로그인되지 않은 경우
                    var loginUrl = "{% url 'community:login' %}";
                    window.location.href = loginUrl;
                }
            });
        });
    </script>
{% endblock %}

{% block main_area %}
    <div class="activity_title"><h1>팀 모집 게시판</h1></div>
    <hr>

    <br><br>

    <button id="createPostBtn">팀원 모집 글쓰기</button>

    {% if team_list.exists %}
        <table class="list_table">
            <thead>
            <tr>
                <th>번호</th>
                <th>제목</th>
                <th>작성날짜</th>
            </tr>
            </thead>
            <tbody>
            {% for team in team_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'community:team_detail' team.id %}">{{ team.title }}</a></td>
                    <td>{{ team.time }}</td>
                </tr>
                <tr>
                    <td colspan="3">
                        <hr>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h1>아직 팀 게시글이 없습니다.</h1>
    {% endif %}

{#    <!-- 페이징 부분은 필요에 따라 수정하세요 -->#}
{#    <div class="pagination">#}
{#        <span class="step-links">#}
{#            {% if post_list.has_previous %}#}
{#                <a href="?page=1">&laquo; first</a>#}
{#                <a href="?page={{ post_list.previous_page_number }}">previous</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current">#}
{#                페이지 {{ post_list.number }} / {{ post_list.paginator.num_pages }}.#}
{#            </span>#}
{##}
{#            {% if post_list.has_next %}#}
{#                <a href="?page={{ post_list.next_page_number }}">next</a>#}
{#                <a href="?page={{ post_list.paginator.num_pages }}">last &raquo;</a>#}
{#            {% endif %}#}
{#        </span>#}
{#    </div>#}
{##}
{#    <!-- 추가된 페이지 링크 부분 -->#}
{#    <div>#}
{#        {% for page_num in post_list.paginator.page_range %}#}
{#            <li>#}
{#                <a href="?page={{ page_num }}">{{ page_num }}</a>#}
{#            </li>#}
{#        {% endfor %}#}
{#    </div>#}
{% endblock %}

community/templates/community/post_team.html
{% extends 'community/base.html' %}
{% block main_area %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'community/css/postDetailStyle.css' %}">

    <div class="wrapper">
        <div class="content_wrapper">
            <div class="title" style="display: inline;">
                <h3 style="font-weight: bold; margin-right: 10px;">팀모집: </h3>
                <h4>{{ post.title }}</h4>
                <br/>
            </div>
            
            <div class="content_nav">
                <a href="#">팀원모집</a>
            </div>
            
            <div class="content_box">
                {% if teams_related_to_post %}
                    <table>
                        <tbody>
                            {% for team in teams_related_to_post %}
                                <tr>
                                    <td>
                                        <a href="{% url 'community:team_detail' team.id %}">
                                            <h2>{{ team.title }}</h2>
                                            <p>{{ team.time }}</p>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <hr class="post-separator">
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h3>아직 팀 게시글이 없습니다.</h3>
                {% endif %}
                
                <br/>
                
                <!-- 팀원 모집 글쓰기 버튼 인라인 스타일 -->
                <button id="createPostBtn" style="color: aliceblue; background-color: #5a32fb; box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3); border-radius: 20px; border: none; outline: none !important; width: 150px; height: 40px;" onclick="redirectToTeamPostForm()">팀원 모집 글쓰기</button>
                <!-- 팀원 모집 글쓰기 버튼 종료  -->
            </div>
        </div>
    </div>
    
    <br/>
    
    <script>
        document.getElementById('createPostBtn').addEventListener('click', function () {
            var isLoggedIn = {% if user.is_authenticated %} true {% else %} false {% endif %};
            
            if (isLoggedIn) {
                // 로그인된 경우
                var teamPostFormUrl = "{% url 'community:TeamPostForm' %}";
                window.location.href = teamPostFormUrl;
            } else {
                // 로그인되지 않은 경우
                var loginUrl = "{% url 'community:login' %}";
                window.location.href = loginUrl;
            }
        });
    </script>
    
{% endblock %}

community/templates/community/user_detail.html
{% extends 'community/base.html' %}
{% block main_area %}
{% load static %}
    <link href="{% static 'community/css/mypage.css' %}" rel="stylesheet" type="text/css">



 <div class="row" style="margin-left: 30px;"> 
        <div class="col-4">
              <h4>회원 정보</h4>  
                    <div class="card my-info">
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                          <div style="display: flex;">
                            <span>아이디</span>
                            <span style="color: gray; margin-left: auto;">{{ user.username }}</span>
                          </div>
                        </li>

                        <li class="list-group-item">
                          <div style="display: flex;">
                            <span>이메일</span>
                            <span style="color: gray; margin-left: auto;">{{ user.email }}</span>
                          </div>
                        </li>

                        <li class="list-group-item">
                          <div style="display: flex;">
                            <a href="{% url 'community:modMajor' pk=user.pk %}" class="postLink">관심전공</a>
                            <span style="color: gray; margin-left: auto;">
                                {% for major in current_user_majors %}
                                  <span style="display: block; text-align: right;">{{ major.majorname }}</span>
                                {% endfor %}
                            </span>
                          </div>
                        </li>

                      </ul>
                    </div>

                      <a href="{% url 'community:modMajor' pk=user.pk %}" class="btn btn-primary btn active mod" role="button" aria-pressed="true" style="background-color: #5a32fb; color:white;">수정</a>


                  <h4>맞춤 키워드</h4>
                  <div class="card my-info">
                    <div class="card-body keywordsField">
                      {% for keyword in current_user_keywords %}
                        <div class="keyword-box">{{ keyword.keywordname }}</div>
                      {% endfor %}
                      <a class="keyword-box mod-box" href="{% url 'community:modKeyword' pk=user.pk %}" role="button">+</a>
                    </div>
                  </div>

                    <!-- <a href="{% url 'community:modKeyword' pk=user.pk %}" class="btn btn-primary btn active mod" role="button" aria-pressed="true">수정</a> -->

                    
                    <div class="card" style="width: 20rem; margin-top: 25px;">
                      <div class="card-body">
                        <a href="{% url 'community:myTeam_detail' pk=user.pk %}" class="postLink">내가 쓴 글</a>
                      </div>
                    </div>
  
                    <div class="card" style="width: 20rem;">
                      <div class="card-body">
                        <a href="{% url 'community:my_comment' pk=user.pk %}" class="postLink">내가 쓴 댓글</a>
                      </div>
                    </div>
              </div>

          <div class="col-8" style="padding-left: 25px;">
              <h4>스크랩한 활동</h4>
              <ul class="scrapUl">
                {% for scrap in current_user_scraps %}
                <div class="card scrapcard">
                  {% if scrap.post.img %}
                    <img src="{{ scrap.post.img }}" class="card-img-top" alt="...">
                  {% else %}
                    {% with random_image=selected_images|random %}
                    <img src="{% static 'community/dukse/' %}{{ random_image }}" alt="덕새 이미지" class="card-img-top" alt="Default Image" height="170px;" />
                    {% endwith %}
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'community:post_detail' pk=scrap.post.id  %}" class="scrapUrl">{{ scrap.post.title|truncatechars:24 }}</a><hr></h5>
                    <p class="card-text scrapcard-text">{{ scrap.post.content|truncatechars:100 }}</p>
                    <div style="text-align: right;">
                      <button type="button" class="btn btn-secondary cancel-button" onclick="cancelScrap('{{ scrap.post.id }}', this)">삭제</button>
                  </div>
                  </div>
                </div>
                </select>
                {% endfor %}
              </ul>
          </div>
      </div>
  </div>

<script>

  function cancelScrap(postId, button) {
        const url = `/community/cancelScrap/`;
        console.log(url);

        // Ajax 요청 보내기
        $.ajax({
            type: 'GET',
            url: url,
            data: {'postId': postId},
            success: function(data) {
              console.log('성공')
              const cardToRemove = button.closest('.card');
              if (cardToRemove) {
                cardToRemove.remove();
              }
            },
            error: function(error) {
                console.log('에러 발생:', error);
            }
        });
    }
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>


{% endblock %}